// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCWANXkXDQnkzmSMnXp34ZdzWtrdtZpUw',
    appId: '1:179902973866:web:91700444627d23e7a88dd3',
    messagingSenderId: '179902973866',
    projectId: 'ash-shifa-ruqyah',
    authDomain: 'ash-shifa-ruqyah.firebaseapp.com',
    databaseURL: 'https://ash-shifa-ruqyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ash-shifa-ruqyah.firebasestorage.app',
    measurementId: 'G-GWKXB4CYHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejT4DZAWUZlJn6QWPhzSm-OrqUNP1B38',
    appId: '1:179902973866:android:9e2fbcfa012cc426a88dd3',
    messagingSenderId: '179902973866',
    projectId: 'ash-shifa-ruqyah',
    databaseURL: 'https://ash-shifa-ruqyah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ash-shifa-ruqyah.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQjTXkEJdIIF8kCTIC6mpN0r7hnS7En0',
    appId: '1:179902973866:ios:b24bd6d66d4bfa0aa88dd3',
    messagingSenderId: '179902973866',
    projectId: 'ash-shifa-ruqyah',
    storageBucket: 'ash-shifa-ruqyah.firebasestorage.app',
    iosBundleId: 'com.example.ashShifaRuqyah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQjTXkEJdIIF8kCTIC6mpN0r7hnS7En0',
    appId: '1:179902973866:ios:81b636ebdda218b0a88dd3',
    messagingSenderId: '179902973866',
    projectId: 'ash-shifa-ruqyah',
    storageBucket: 'ash-shifa-ruqyah.firebasestorage.app',
    iosBundleId: 'com.example.ashShifaRuqyah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCWANXkXDQnkzmSMnXp34ZdzWtrdtZpUw',
    appId: '1:179902973866:web:7a3fe23b8574eb74a88dd3',
    messagingSenderId: '179902973866',
    projectId: 'ash-shifa-ruqyah',
    authDomain: 'ash-shifa-ruqyah.firebaseapp.com',
    storageBucket: 'ash-shifa-ruqyah.firebasestorage.app',
    measurementId: 'G-L9YMQFKZ73',
  );

}
